default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "luxecart_user") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "luxecart_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "luxecart_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PRODUCTION", "luxecart_production") %>