# Default environment
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: luxecart_development

test:
  <<: *default
  database: luxecart_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: luxecart_production